### ISSUE TITLE
Resposive design

### ISSUE THREAD

**Issue by DanaVarahi** [blockpress/blockpress.me#12]
Make sure all the themes have responsive design features enabled and functional. 

* [x] `metaverse` theme
* [x] `trollfell` theme
* [x] `fluxstate` theme
* [x] `amber` theme

**Comment by antonchanning** [comment]
I've assigned myself to look at responsiveness for the `fluxstate` theme as I will already be looking at it for palette support.

**Comment by antonchanning** [comment]
Just my part of this left to do...

**Comment by antonchanning** [comment]
This is now done.
