### ISSUE TITLE
Thumbnails not showing in post listing.

### ISSUE THREAD

**Issue by antonchanning** [blockpress/blockpress.me#37]
By default we were hiding post thumbnails in css and then using jquery to show them for posts that have them. This prevented the display of broken image thumbnails beside posts that don't have one.

This was working but something broke it, and now no thumbnails display ever.

This needs fixing before release of beta.

**Comment by DanaVarahi** [comment]
The bug is most likely in steem.js file line 54 onwards. The function is called in steem-posts.html line 7.

The function steemPostsDisplayThumbnail specifies CSS display and width. This could conflict with new themes. It's not related to this bug but worth noting.

**Comment by DanaVarahi** [comment]
Another thing I noticed is that steemPostsDisplayThumbnail function is called from steem-posts.html using hardcoded onload. It would be better to change this.

**Comment by antonchanning** [comment]
Yes. If each image had a standard thumbnail class, and a unique id, the onload event could be added to them all _en masse_. In the function, if the id of the thumbnail ended with the post permlink, it could be used to calculate the id of the containing div and apply the class changes.
