### ISSUE TITLE
Copy Writing Proposal 

### ISSUE THREAD

**Issue by Gallantmayor** [blockpress/blockpress.me#44]
Hello, i just checked your lovely project and i discovered you have some sections missing out like FAQ, about us, contact us and privacy policy. If you dont mind i will like to write that for you.
My email: gallantmayor22@gmail.com

**Comment by antonchanning** [comment]
Do you have links to examples of your prior work?

**Comment by antonchanning** [comment]
I'm going to close this issue. If you want to reopen, please feel free to answer my above question.

Thanks.
